#!/usr/bin/env python
import sys, secrepo
#
# All the logic is in the secrepo module.
#
if len(sys.argv) > 1:
    rc = secrepo.srdiff_cmd(sys.argv[1:],True)
else:
    rc = secrepo.srsmudge_cmd(sys.argv[1:],True)

sys.exit(rc)
